highlighter: rouge
markdown: kramdown
permalink: pretty
paginate: 5
paginate_path: ":num"
excerpt_separator: ""
timezone: UTC
plugins:
  - jekyll-paginate
  - jekyll-titles-from-headings
  - jekyll-twitter-plugin
  - jekyll-youtube
  - jekyll-sitemap
titles_from_headings:
  enabled: true
  strip_title: true
  collections: true
url: http://jcazevedo.net
exclude:
  - Rakefile
  - README.md
collections:
  posts:
    permalink: /:year/:month/:day/:title:output_ext
