highlighter: pygments
markdown: kramdown
permalink: pretty
paginate: 5
paginate_path: "posts/:num"
excerpt_separator: ""
plugins: [jekyll-paginate, jekyll_figure]
figures:
  dir: /img
url: http://jcazevedo.net
