highlighter: rouge
markdown: kramdown
permalink: pretty
paginate: 5
paginate_path: "posts/:num"
excerpt_separator: ""
plugins:
  - jekyll-paginate
  - jekyll-titles-from-headings
  - jekyll-twitter-plugin
  - jekyll-youtube
titles_from_headings:
  enabled: true
  strip_title: true
  collections: true
url: http://jcazevedo.net
