source 'https://rubygems.org'

gem 'html-proofer', '4.4.0'
gem 'jekyll', '4.2.2'
gem 'jekyll-paginate', '1.1.0'
gem 'jekyll-titles-from-headings', '0.5.3'
gem 'jekyll-twitter-plugin', '2.1.0'
gem 'jekyll-youtube', '1.0.0'
gem 'rb-fsevent', '0.11.2'
gem 'webrick', '1.7.0'
