source 'https://rubygems.org'

gem 'html-proofer', '3.9.2'
gem 'jekyll', '3.8.5'
gem 'jekyll-paginate', '1.1.0'
gem 'jekyll-titles-from-headings', '0.5.1'
gem 'jekyll-twitter-plugin', '2.0.0'
gem 'jekyll-youtube', '1.0.0'
gem 'jekyll_figure', '0.0.3'
gem 'pygments.rb', '1.2.1'
gem 'rb-fsevent', '0.10.3'
