source 'https://rubygems.org'

gem 'html-proofer', '3.7.2'
gem 'jekyll', '3.5.0'
gem 'jekyll-paginate', '1.1.0'
gem 'jekyll-titles-from-headings', '0.5.0'
gem 'jekyll-twitter-plugin', '2.0.0'
gem 'jekyll-youtube', '1.0.0'
gem 'jekyll_figure', '0.0.3'
gem 'pygments.rb', '1.1.2'
gem 'rb-fsevent', '0.9.8'
